/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "airports.h"
#include <stdio.h>
#include <string.h>

airports_ret *
getairports_1_svc(struct coordinates *argp, struct svc_req *rqstp)
{
	static airports_ret  result;
	/*view incoming values from the client-places_server*/
	printf("\nAirport Server Side: received lat= %f, received lon= %f\n", argp[0].lat, argp[0].lon);

	/*assign arg from places server into coordinates struct*/
	struct coordinates location;
	location.lat = argp[0].lat;
	location.lon = argp[0].lon;
	printf("\nAirport Server side: assigned lat= %f, assigned lon= %f\n", location.lat, location.lon);

	/***
	*		Call to File operations goes here
	*
	*/

	/*assign airport structures*/
	airport* ap = &result.airports_ret_u.airport;
	airport p;

	/*hardcode airport struct for roundtrip test*/
	char* c;
	char* s;
	strncpy(c, "Portland", 10);
	strncpy(s, "OR", 4);
	printf("\nHardcoded city = %s, state= %s\n", c, s);
	strncpy(p->city, c, sizeof(p->city) - 1);
	strncpy(p->state, s, sizeof(p->state) - 1);
	printf("\nAirport server side: p->city= %s, p->state= %s\n", p->city, p->state);

	/*return result to places server*/
	p->next = NULL;
	printf("\np->next = NULL;\n");
	*ap = p;
	printf("\n*ap = p;\n");
	printf("\nReturning\n");

	return &result;
}
