/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "airports.h"

places_ret *
getairports_1_svc(coordinates *argp, struct svc_req *rqstp)
{
	static places_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}
