/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct airport_place_node *airport_place;

typedef char airport_place_code[4];

typedef char city_place_name[64];

typedef char state_place_initials[3];

struct airport_place_node {
	airport_place_code airport_place;
	city_place_name city;
	state_place_initials state;
	double distance;
	airport_place next;
};
typedef struct airport_place_node airport_place_node;

struct city_state {
	city_place_name city;
	state_place_initials state;
};
typedef struct city_state city_state;

struct places_ret {
	int err;
	union {
		airport_place airport_place;
	} places_ret_u;
};
typedef struct places_ret places_ret;

#define PLACES_PROG 0x20000025
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALLPLACES 1
extern  places_ret * callplaces_1(city_state *, CLIENT *);
extern  places_ret * callplaces_1_svc(city_state *, struct svc_req *);
extern int places_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALLPLACES 1
extern  places_ret * callplaces_1();
extern  places_ret * callplaces_1_svc();
extern int places_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_airport_place (XDR *, airport_place*);
extern  bool_t xdr_airport_place_code (XDR *, airport_place_code);
extern  bool_t xdr_city_place_name (XDR *, city_place_name);
extern  bool_t xdr_state_place_initials (XDR *, state_place_initials);
extern  bool_t xdr_airport_place_node (XDR *, airport_place_node*);
extern  bool_t xdr_city_state (XDR *, city_state*);
extern  bool_t xdr_places_ret (XDR *, places_ret*);

#else /* K&R C */
extern bool_t xdr_airport_place ();
extern bool_t xdr_airport_place_code ();
extern bool_t xdr_city_place_name ();
extern bool_t xdr_state_place_initials ();
extern bool_t xdr_airport_place_node ();
extern bool_t xdr_city_state ();
extern bool_t xdr_places_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
